version: '3.8'

services:
  db:
    image: postgres:13
    container_name: capybara_postgres
    environment:
      POSTGRES_DB: capybara_dating_app
      POSTGRES_USER: capybara_user
      POSTGRES_PASSWORD: capybara_password
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
